# Generated by Django 4.1.4 on 2022-12-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binicarproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='km',
            field=models.CharField(max_length=150),
        ),
    ]
