# Generated by Django 4.1.4 on 2022-12-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binicarproject', '0002_alter_homepage_km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='km',
        ),
    ]
