# Generated by Django 4.1.4 on 2022-12-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binicarproject', '0003_remove_homepage_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='price',
            field=models.CharField(max_length=150),
        ),
    ]
