# Generated by Django 4.1.4 on 2022-12-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homecars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('model', models.TextField()),
                ('price', models.IntegerField()),
                ('transmition', models.CharField(max_length=150)),
                ('original', models.CharField(max_length=150)),
                ('cc', models.CharField(max_length=150)),
                ('plate', models.CharField(max_length=150)),
                ('condition', models.CharField(max_length=150)),
            ],
        ),
    ]
